services:
    l2-stealer:
        build: .
        volumes:
            - ..:/workspaces/lab2
        # Prevent container from instantly exiting, allowing us to attach terminal
        command: /bin/sh -c "sleep infinity"
